# Site settings
author: Samantha Wabi
title: Journey to My Full Potential
header-img: img/home-bg.png
email: swfullpotential@gmail.com
copyright_name: Samantha Wabi
description: > # this means to ignore newlines until "baseurl:"
  Forever improving and growing. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SWFullPotential

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
